version: "3"

services:
  local-inferencer-cpu:
    image: muhandre/fogverse:local-inferencer-cpu
    volumes:
      - ./local-inferencer/logs/cpu/:/app/logs/
    environment:
      - CONSUMER_SERVERS=localhost:9094
      - PRODUCER_SERVERS=localhost:9094
      - CONSUMER_TOPIC=input
      - ARCHITECTURE=only_local
      - UAV_COUNT=1
      - ATTEMPT=1
    restart: always
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
              device_ids: ['0']