version: "3"

services:
  local-inferencer:
    image: muhandre/fogverse:local-inferencer
    volumes:
      - ./local-inferencer/logs/:/app/logs/
    environment:
      - CONSUMER_SERVERS=localhost:9094
      - PRODUCER_SERVERS=localhost:9094
      - CONSUMER_TOPIC=input
      - ARCHITECTURE=with_cloud
      - UAV_COUNT=1
      - ATTEMPT=1
    restart: always
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]

  local-preprocess:
    image: muhandre/fogverse:local-preprocessor
    volumes:
      - ./local-preprocessor/logs/:/app/logs/
    environment:
      - CONSUMER_SERVERS=localhost:9094
      - PRODUCER_SERVERS=localhost:9094
      - CONSUMER_TOPIC=input
      - PRODUCER_TOPIC=preprocessed
      - UAV_COUNT=1
      - ATTEMPT=1
    restart: always
    network_mode: host

  local2cloud-forwarder:
    image: muhandre/fogverse:forwarder
    volumes:
      - ./forwarder/logs/:/app/logs/
    environment:
      - CONSUMER_SERVERS=localhost:9094
      - PRODUCER_SERVERS=34.101.190.243:9095
      - CONSUMER_TOPIC=preprocessed
      - PRODUCER_TOPIC=preprocessed
      - ROLE=local2cloud
      - UAV_COUNT=1
      - ATTEMPT=1
    restart: always
    network_mode: host

  cloud2local-forwarder:
    image: muhandre/fogverse:forwarder
    volumes:
      - ./forwarder/logs/:/app/logs/
    environment:
      - CONSUMER_SERVERS=34.101.190.243:9095
      - PRODUCER_SERVERS=localhost:9094
      - CONSUMER_TOPIC=result
      - PRODUCER_TOPIC=result
      - ROLE=cloud2local
      - UAV_COUNT=1
      - ATTEMPT=1
    restart: always
    network_mode: host

  merger:
    image: muhandre/fogverse:merger
    volumes:
      - ./merger/logs/:/app/logs/
    environment:
      - CONSUMER_SERVERS=localhost:9094
      - PRODUCER_SERVERS=localhost:9094
      - WAIT_THRESH=4000
      - UAV_COUNT=1
      - ATTEMPT=1
    restart: always
    network_mode: host
