version: "3"

services:
  local-executor:
    image: muhandre/fogverse:local-executor-cam
    volumes:
      - ./local-executor/cam/logs/:/app/logs/
    environment:
      - CONSUMER_SERVERS=localhost:9094
      - PRODUCER_SERVERS=localhost:9094
      - CONSUMER_TOPIC=input
      - ARCHITECTURE=with_cloud
    restart: always
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]

  local-preprocessor:
    image: muhandre/fogverse:local-preprocessor-pillow-compression
    volumes:
      - ./local-preprocessor/pillow-compression/logs/:/app/logs/
    environment:
      - CONSUMER_SERVERS=localhost:9095
      - PRODUCER_SERVERS=localhost:9095
      - CONSUMER_TOPIC=input
      - PRODUCER_TOPIC=preprocessed
    restart: always
    network_mode: host

  local2cloud-forwarder:
    image: muhandre/fogverse:forwarder
    volumes:
      - ./forwarder/logs/local2cloud/:/app/logs/
    environment:
      - CONSUMER_SERVERS=localhost:9094
      - PRODUCER_SERVERS=34.101.244.110:9095
      - CONSUMER_TOPIC=preprocessed
      - PRODUCER_TOPIC=preprocessed
      - ROLE=local2cloud
    restart: always
    network_mode: host

  cloud2local-forwarder:
    image: muhandre/fogverse:forwarder
    volumes:
      - ./forwarder/logs/cloud2local/:/app/logs/
    environment:
      - CONSUMER_SERVERS=34.101.244.110:9095
      - PRODUCER_SERVERS=localhost:9095
      - CONSUMER_TOPIC=result
      - PRODUCER_TOPIC=result
      - ROLE=cloud2local
    restart: always
    network_mode: host

  merger-sorter:
    image: muhandre/fogverse:merger-sorter-cam
    volumes:
      - ./merger-sorter/cam/logs/:/app/logs/
    environment:
      - CONSUMER_SERVERS=localhost:9094
      - PRODUCER_SERVERS=localhost:9094
      - WAIT_THRESH=4000
    restart: always
    network_mode: host
