version: "3"

services:
  cloud-inferencer:
    image: muhandre/fogverse:cloud-inferencer
    volumes:
      - ./logs/:/app/logs/
    environment:
      - CONSUMER_SERVERS=10.184.0.11:9094
      - PRODUCER_SERVERS=10.184.0.11:9094
      - CONSUMER_TOPIC=preprocessed
      - PRODUCER_TOPIC=result
