version: "3"

networks:
  kafka-net:
    driver: bridge

services:
  zookeeper:
    image: "bitnami/zookeeper:latest"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-net
  broker-0:
    image: "bitnami/kafka:latest"
    ports:
      - "9094:9094"
      - "9096:9096"
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTER_BROKER:PLAINTEXT,SAME_HOST:PLAINTEXT,EXTERNAL_PRIVATE:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTER_BROKER://:9092,SAME_HOST://:9094,EXTERNAL_PRIVATE://:9096
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTER_BROKER://broker-0:9092,SAME_HOST://localhost:9094,EXTERNAL_PRIVATE://192.168.137.1:9096
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTER_BROKER
      - KAFKA_ENABLE_KRAFT=no
    networks:
      - kafka-net
    depends_on:
      - zookeeper
  broker-1:
    image: "bitnami/kafka:latest"
    ports:
      - "9095:9095"
      - "9097:9097"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTER_BROKER:PLAINTEXT,SAME_HOST:PLAINTEXT,EXTERNAL_PRIVATE:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTER_BROKER://:9092,SAME_HOST://:9095,EXTERNAL_PRIVATE://:9097
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTER_BROKER://broker-1:9092,SAME_HOST://localhost:9095,EXTERNAL_PRIVATE://192.168.137.1:9097
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTER_BROKER
      - KAFKA_ENABLE_KRAFT=no
    networks:
      - kafka-net
    depends_on:
      - zookeeper
