# Note: Multi node cluster -> https://www.youtube.com/watch?v=3Ne2a5_pREs
# Sepertinya gapapa inter.broker.listerner nya cuma satu, soalnya namanya cuma bisa satu. -> https://www.confluent.io/blog/kafka-listeners-explained/
version: "3"

services:
  broker:
    image: "muhandre/fogverse:kafka-3.1"
    ports:
      - "9092:9092"
      - "9094:9094"
      - "9095:9095"
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_CFG_ZOOKEEPER_CONNECT=10.184.0.3:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTER_BROKER:PLAINTEXT, EXTERNAL_PRIVATE:PLAINTEXT, EXTERNAL_PUBLIC:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTER_BROKER://:9092, EXTERNAL_PRIVATE://:9094, EXTERNAL_PUBLIC://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTER_BROKER://10.184.0.4:9092, EXTERNAL_PRIVATE://10.184.0.4:9094, EXTERNAL_PUBLIC://34.101.148.109:9095
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTER_BROKER
      - KAFKA_ENABLE_KRAFT=no
