FROM ubuntu:20.04

ENV TZ=Asia/Jakarta

RUN --mount=type=cache,target=/var/cache/apt_update apt update \
    && apt install -y --no-install-recommends \
        python-is-python3 \
        python3-pip \
        python3-dev \
        ffmpeg libsm6 libxext6 \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip \
    numpy opencv-python
