FROM muhandre/pytorch:v1.10-py3.8.2-yolov5-cpu

RUN --mount=type=cache,target=/var/cache/apt_update apt update \
    && apt install -y \
    libssl-dev \
    zlib1g-dev \
    gcc \
    vim \
    g++

RUN pip3 install pandas aiokafka
