version: "3"

services:
  local-preprocess:
    image: muhandre/fogverse:local-preprocess
    volumes:
      - ./logs/:/app/logs/
    environment:
      - CONSUMER_SERVERS=localhost:9094
      - PRODUCER_SERVERS=localhost:9094
      - CONSUMER_TOPIC=input
      - PRODUCER_TOPIC=preprocessed
    restart: always
    network_mode: host
