version: "3"

services:
  local-inferencer:
    image: muhandre/fogverse:try-client-local
    environment:
      - CONSUMER_SERVERS=localhost:9094
      - CONSUMER_TOPIC=result
    restart: always
    network_mode: host
